# Generated by Django 3.1 on 2020-08-12 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CosmeticIngredient',
        ),
    ]
