# Generated by Django 3.1 on 2020-08-12 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0002_delete_cosmeticingredient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CosmeticProduct',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerProduct',
        ),
        migrations.DeleteModel(
            name='CustomerStatus',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
