# Generated by Django 3.1 on 2020-08-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodlinebot', '0003_auto_20200812_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStatus',
            fields=[
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('continuous', models.IntegerField(blank=True, null=True)),
                ('nid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
