# Generated by Django 3.1 on 2020-08-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0005_auto_20200812_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('cnt', models.IntegerField()),
                ('continuous', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'CustomerState',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.TextField(default='song')),
                ('singer', models.TextField(default='AKB48')),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'music',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('pname', models.TextField()),
                ('pbrand', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'CustomerProduct',
            },
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
