# Generated by Django 3.1 on 2020-08-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0006_auto_20200812_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosmeticProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField()),
                ('brand', models.TextField()),
                ('pname', models.TextField()),
                ('char', models.TextField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'Cosmetic_Product',
            },
        ),
    ]
