# Generated by Django 3.1 on 2020-08-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0007_cosmeticproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosmeticIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.TextField()),
                ('ingredient', models.TextField()),
                ('acne', models.TextField()),
                ('pchar', models.TextField()),
                ('dalton', models.TextField()),
                ('safeness', models.TextField()),
                ('stimulation', models.TextField()),
                ('score', models.TextField()),
            ],
            options={
                'db_table': 'Cosmetic_Ingredient',
            },
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('pname', models.TextField()),
                ('pbrand', models.TextField()),
                ('fit_prod', models.TextField()),
                ('unfit_prod', models.TextField()),
                ('reg_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'User_Product',
            },
        ),
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.AlterModelTable(
            name='customerstate',
            table='Customer_State',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Customer_Product',
        ),
    ]
